### ISSUE TITLE
新版本不能用了！ 初始化游戏数据失败: 605|1|2

### ISSUE THREAD

**Issue by dabbad201141** [JX3Toy/jx3toy.github.io#2]
20:08:12 等待游戏启动...
20:08:12 正在获取版本数据...
20:08:14 等待游戏启动完成...
20:08:14 正在初始化游戏数据...
20:08:15 初始化游戏数据失败: 605|1|2

**Comment by JX3Toy** [comment]
知道了，会尽快更新

**Comment by dabbad201141** [comment]
16:30:08 等待游戏启动...
16:30:11 正在获取版本数据...
16:30:13 等待游戏启动完成...
16:30:13 正在初始化游戏数据...
16:30:13 初始化游戏数据失败: 615|1|2

**Comment by dabbad201141** [comment]
这是另一台电脑的
